modLoader="javafml"
loaderVersion="[47,)"
license="MIT"

[[mods]]
modId="undergarden"
version="${file.jarVersion}"
displayName="The Undergarden"
logoFile="logo.png"
logoBlur=false
authors="quek, slbsh"
description='''Deep underground, a forgotten land awaits.'''

[[dependencies.undergarden]]
	modId="forge"
	mandatory=true
	versionRange="[47,)"
	ordering="NONE"
	side="BOTH"

[[dependencies.undergarden]]
	modId="minecraft"
	mandatory=true
	versionRange="[1.20,1.21)"
	ordering="NONE"
	side="BOTH"

[[dependencies.undergarden]]
	modId="adresources"
	mandatory=true
	versionRange="[0,)"
	ordering="NONE"
	side="BOTH"
